### ISSUE TITLE
Conduct a webinar on the topic within the DataONE Webinar series

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/RepositoryFinder#5]

**Comment by aebudden** [comment]
Possible options are December 8th (during AGU) or January 12th (before ESIP winter meeting) or February 9th. Preference for January 12th as things need to be (near) complete by then and can include in ESIP winter meeting report out.

**Comment by erinlynmclean** [comment]
I can be the person who takes point on this if you'd like

**Comment by aebudden** [comment]
Scheduled for January 12th. See https://www.dataone.org/webinars/repo-discovery/
